### ISSUE TITLE
Hide blue line on native mobile

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#10102]
## Overview 

On native mobile, blue line sometimes shows above action sheet.

### AC 

Repro the blue line and then remove if possible. Might be an iphone select behavior. 

## Figma link or Screenshots 

[Screen Recording Jul 25 2025.mov](https://uploads.linear.app/ed5193d7-27ef-4be2-b461-c7791d75bc4f/35bfa8dd-869c-4948-acdb-429c278a61b1/1fa54e4f-154a-4634-985d-c844f33fe0f8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2VkNTE5M2Q3LTI3ZWYtNGJlMi1iNDYxLWM3NzkxZDc1YmM0Zi8zNWJmYThkZC04NjljLTQ5NDgtYWNkYi00MjljMjc4YTYxYjEvMWZhNTRlNGYtMTU0YS00NjM0LTk4NWQtYzg0NGYzM2ZlMGY4IiwiaWF0IjoxNzUzNDYzNzMwLCJleHAiOjMzMzI0MDIzNzMwfQ.ld7a-CV7CWFE7X4U5ZqRI4ZwaYnW-h7d1h6t6HCXQlg)

## Rough how to fix \[Eng\]

Breakdown a path to solve for acc or any reference material, docs. A place for estimation notes or initial comments for solutions.

**Comment by NeOMakinG** [comment]
I couldn't reproduce this one, it's quite easy to fix if we find a way to 100% reproduce it, if someone comes here:

You have an example on how to fix that in https://github.com/shapeshift/web/commit/a682a3821b1f8ab0c66b8bbd3b7721a3889462ba#diff-59db6022558e8c382823aa3981bd000b4be8237d84a7c9ef83f33ee61408513eR9-R57

This is `WebkitTapHighlightColor` to make transparent, it's useful on buttons and clickable elements but sometime if the focus is on a big pan it's quite useless

But I found a bunch of bugs on mobile and responsive that I fixed in https://github.com/shapeshift/web/pull/10140

PS: sorry it wasn't in the cycle but I wanted to take a quick thing before leaving

**Comment by NeOMakinG** [comment]
Can we reproduce that before adding it to any grooming?<br><br>We discussed that with @0xApotheosis and maybe we could disable this webkit feature entirely for absolutely every elements of the dom, it would be quite a one liner in our global theme, as it feels most of the time annoying and chakra is supposed to support focused state for almost every important elements

**Comment by 0xApotheosis** [comment]
I still get it some times, but it's really hard to reproduce. Maybe lets just close this guy!
