### ISSUE TITLE
Unable to deposit into WETH vault

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4213]
### Overview

When trying to deposit into the WETH vault is gives a 'Something went wrong' error

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to the Earn page and find and select WETH in the asset tab
3) Choose a position to stake into and select continue
4) Deposit into the vault, selecting amount and then continue
5) Note if you havent approved the contract to interact with WETH then you will need to do this (NOTE: when approving, it will say something went wrong as if the transaction didnt complete. However, the transaction does broadcast and the tx can be seen in transaction history)
6) If approved, select Continue on the amount to deposit. Note the "Something went wrong error" appears and the load circle spins continuously on the Continue button.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/100157997/230689147-d3d7660b-bc44-4388-9be9-5458112fb553.png">
<img width="238" alt="image" src="https://user-images.githubusercontent.com/100157997/230689283-001d399a-5226-4df4-a257-a5e36b494ba0.png">

### Acceptance Criteria

Should be able to deposit into WETH vault

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
@MBMaria can you please retest? there have been a lot of changes in this part of the codebase since this ticket was written

**Comment by MBMaria** [comment]
@0xdef1cafe ill check this when gas goes down. currently sitting at $66 to try to deposit.

**Comment by gomesalexandre** [comment]
@MBMaria currently discussing this one out with the Idle team - looks like there is no eng. work needed. This should work as soon as the CDO is properly added to the registry

**Comment by gomesalexandre** [comment]
@MBMaria The issue has been fixed upstream for WETH MorphoAAVE pools (which is the ones that were throwing the error you've posted), can we retest and close this ? 🙏🏽

**Comment by MBMaria** [comment]
I just tried to check now and gas is about $50 to deposit so ill wait until
its come down before testing.

**Comment by gomesalexandre** [comment]
Np @MBMaria, let me know when that's retested and feel free to close this after confirming it went through with no hassle.

**Comment by purelycrickets** [comment]
@MBMaria can we see if this is still an issue?

**Comment by MBMaria** [comment]
looks like this is still an issue
![image](https://github.com/shapeshift/web/assets/100157997/7230ecd1-d51d-4047-b2d1-567673331516)

**Comment by MBMaria** [comment]
Able to deposit into idle weth vault 
![image](https://github.com/shapeshift/web/assets/100157997/4dd6c827-ad6e-440e-b777-1c758b6fb10f)
